version: "3"
services:
  db:
    image: mongo:6
    environment:
      MONGO_INITDB_ROOT_USERNAME: BQKarlaSara
      MONGO_INITDB_ROOT_PASSWORD: BQKarlaSaraDev007
    volumes:
      - ./db-data:/data/db
    restart: always
    networks:
      - private
      - public
    expose:
      - 27017
    ports:
      - 28017:27017
  node:
    image: node:20
    user: node
    working_dir: /home/node/app
    environment:
      NODE_ENV: production
      PORT: 8080
      DB_URL: mongodb://BQKarlaSara:BQKarlaSaraDev007@db:27017/BQKarlaSara?authSource=admin
      JWT_SECRET: esta-es-la-api-burger-queen
      ADMIN_EMAIL: admin@prueba
      ADMIN_PASSWORD: changeme
    volumes:
      - ./:/home/node/app
    expose:
      - 8080
    ports:
      - 80:8080
    command: bash -c 'rm -rf node_modules && npm install && npm start'
    depends_on:
      - db
    networks:
      - public
      - private
networks:
  public:
    internal: false
  private:
    internal: true
