version: "3"
services:
  db:
    image: mongo:6
    user: mongo
    environment:
      NODE_ENV: production
      PORT: 27017
      DB_URL: mongodb://127.0.0.1:27017/test
      JWT_SECRET: xxxxxxxx
      ADMIN_EMAIL: admin@localhost
      ADMIN_PASSWORD: changeme
      MONGO_INITDB_ROOT_USERNAME: bq
      MONGO_INITDB_ROOT_PASSWORD: secret
    volumes:
      - ./db-data:/data/db
    restart: always
    networks:
      - private
  node:
    image: node:20
    user: node
    working_dir: /home/node/app
    environment:
      NODE_ENV: production
      PORT: 8080
      DB_URL: http://localhost:8080/test
      JWT_SECRET: xxxxxxxx
      ADMIN_EMAIL: admin@localhost
      ADMIN_PASSWORD: changeme
    volumes:
      - ./db-data:/data/node
      - 8080
    ports:
      - 80:8080
    command: bash -c 'rm -rf node_modules && npm install && npm start'
    depends_on:
      - db
    networks:
      - private
networks:
  public:
    internal: false
  private:
    internal: true
